[project]
name = "Eli extraction"
version = "0.1.0"
description = "dependencies for get_mail_from_pdf.py and extract_emails_from_pdfs.py files."
readme = "../README.md"
requires-python = ">=3.13"
dependencies = [
    "lxml>=6.0.2",
    "pypdf>=6.1.2",
]
